pub mod customer_handler;
pub mod organisation_handler;
pub mod invoice_handler;
pub mod incoming_invoice_handler;
pub mod expense_handler;
pub mod users;
pub mod purchase_order_handler;
pub mod cost_center_handler;
pub mod salary_handler;
pub mod general_expense_handler;
pub mod challan_handler;
pub mod category_handler;
pub mod product_handler;
pub mod estimate_handler;
pub mod ledger_handler;
pub mod account_handler;

pub use customer_handler::configure_routes as configure_customer_routes;
pub use organisation_handler::{configure_routes as configure_organisation_routes, configure_public_routes as configure_organisation_public_routes};
pub use invoice_handler::configure_routes as configure_invoice_routes;
pub use incoming_invoice_handler::configure_routes as configure_incoming_invoice_routes;
pub use expense_handler::configure_routes as configure_expense_routes;
pub use users::{configure_routes as configure_user_routes, configure_protected_routes as configure_protected_user_routes};
pub use purchase_order_handler::configure_routes as configure_purchase_order_routes;
pub use cost_center_handler::configure_routes as configure_cost_center_routes;
pub use salary_handler::configure_routes as configure_salary_routes;
pub use general_expense_handler::configure_routes as configure_general_expense_routes;
pub use challan_handler::configure_routes as configure_challan_routes;
pub use category_handler::configure_routes as configure_category_routes;
pub use product_handler::configure_routes as configure_product_routes;
pub use estimate_handler::configure_routes as configure_estimate_routes;
pub use ledger_handler::configure_routes as configure_ledger_routes;
pub use account_handler::configure_routes as configure_account_routes;
