$lines = Get-Content src\handlers\invoice_handler.rs
$before = $lines[0..331]
$after = $lines[386..($lines.Length-1)]
$newBody = @(
'    let expense_count = expense_summary.expense_count + general_expense_summary.expense_count;',
'    let total_amount = expense_summary.total_amount + general_expense_summary.total_amount;',
'    let total_tax = expense_summary.total_tax + general_expense_summary.total_tax;',
'    let total_cgst = expense_summary.total_cgst + general_expense_summary.total_cgst;',
'    let total_sgst = expense_summary.total_sgst + general_expense_summary.total_sgst;',
'    let total_igst = expense_summary.total_igst + general_expense_summary.total_igst;',
'    let total_gst_collected = expense_summary.total_gst_collected + general_expense_summary.total_gst_collected;',
'',
'    let net_gst_payable = summary.total_gst_collected - incoming_summary.total_gst_collected - total_gst_collected;',
'',
'    Ok(HttpResponse::Ok().json(json!({',
'        "month": summary.month,',
'        "outgoing_invoices": {',
'            "invoice_count": summary.invoice_count,',
'            "total_cgst": summary.total_cgst,',
'            "total_sgst": summary.total_sgst,',
'            "total_igst": summary.total_igst,',
'            "total_gst_collected": summary.total_gst_collected,',
'            "paid_amount": summary.paid_amount,',
'            "paid_invoice_count": summary.paid_invoice_count',
'        },',
'        "incoming_invoices": {',
'            "invoice_count": incoming_summary.invoice_count,',
'            "total_amount": incoming_summary.total_amount,',
'            "total_cgst": incoming_summary.total_cgst,',
'            "total_sgst": incoming_summary.total_sgst,',
'            "total_igst": incoming_summary.total_igst,',
'            "total_gst_collected": incoming_summary.total_gst_collected,',
'            "paid_amount": incoming_summary.paid_amount,',
'            "paid_invoice_count": incoming_summary.paid_invoice_count',
'        },',
'        "expenses": {',
'            "expense_count": expense_summary.expense_count,',
'            "total_amount": expense_summary.total_amount,',
'            "total_cgst": expense_summary.total_cgst,',
'            "total_sgst": expense_summary.total_sgst,',
'            "total_igst": expense_summary.total_igst,',
'            "total_gst_collected": expense_summary.total_gst_collected',
'        },',
'        "general_expenses": {',
'            "expense_count": general_expense_summary.expense_count,',
'            "total_amount": general_expense_summary.total_amount,',
'            "total_cgst": general_expense_summary.total_cgst,',
'            "total_sgst": general_expense_summary.total_sgst,',
'            "total_igst": general_expense_summary.total_igst,',
'            "total_gst_collected": general_expense_summary.total_gst_collected',
'        },',
'        "combined_expense_gst": {',
'            "expense_count": expense_count,',
'            "total_amount": total_amount,',
'            "total_tax": total_tax,',
'            "total_cgst": total_cgst,',
'            "total_sgst": total_sgst,',
'            "total_igst": total_igst,',
'            "total_gst_collected": total_gst_collected',
'        },',
'        "net_gst_payable": {',
'            "outgoing_gst_collected": summary.total_gst_collected,',
'            "incoming_gst_collected": incoming_summary.total_gst_collected,',
'            "expense_gst_collected": total_gst_collected,',
'            "net_payable": net_gst_payable',
'        }',
'    })))',
'}'
)
$result = $before + $newBody + $after
Set-Content src\handlers\invoice_handler.rs $result
